apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: deeprobin-de-cert
  namespace: default
spec:
  secretName: deeprobin.de-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: deeprobin.de
  dnsNames:
  - deeprobin.de
  - dev.deeprobin.de
  - staging.deeprobin.de
  - traefik.deeprobin.de