name: deploy (staging)

on:
  push:
    branches: [ "staging" ]

jobs:
  push_docker_image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - id: date
      run: echo "::set-output name=date::$(date +%s)"
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: |
            ghcr.io/${{ github.repository_owner }}/homepage:staging-${{ steps.date.outputs.date }}
            ghcr.io/${{ github.repository_owner }}/homepage:staging
  deploy_k8s:
    runs-on: ubuntu-latest
    needs: push_docker_image
    environment:
      name: Staging
      url: https://staging.deeprobin.de
    steps:
      - name: Set the Kubernetes context
        uses: azure/k8s-set-context@v2
        with:
          method: service-account
          k8s-url: https://167.86.76.26:6443
          k8s-secret: ${{ secrets.KUBERNETES_SECRET }}
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Install Helm Chart
        run: helm upgrade --install homepage ./k8s/homepage --values ./k8s/homepage/values.staging.yaml