name: Deploy

on:
  push:
    branches: [ "production" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://deeprobin.de
    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: |
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/homepage:$(date +%s)
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/homepage:latest