name: deploy (production)

on:
  push:
    branches: [ "production" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://deeprobin.de
    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - id: date
      run: echo "::set-output name=date::$(date +%s)"
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: |
            ${{ github.repository_owner }}/homepage:${{ steps.date.outputs.date }}
            ${{ github.repository_owner }}/homepage:latest