name: deploy (staging)

on:
  push:
    branches: [ "staging" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://staging.deeprobin.de
    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - id: date
      run: echo "::set-output name=date::$(date +%s)"
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: |
            ${{ github.repository_owner }}/homepage:staging-${{ steps.date.outputs.date }}
            ${{ github.repository_owner }}/homepage:staging